{{- if .Values.CoreGKESA }}
apiVersion: v1
data:
  filename: {{ .Values.CoreGKESA.Filename | b64enc | quote }}
  data: {{ .Values.CoreGKESA.Data | b64enc | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: secretFile
  name: core-sa
type: Opaque
{{- end }}