{{- if .Values.KanikoSecret }}
apiVersion: v1
data:
  kaniko-secret: {{ .Values.KanikoSecret.Data | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    # Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: secretText
  name: kaniko-secret
type: Opaque
{{- end }}
