{{- if .Values.TestJenkinsUser }}
apiVersion: v1
data:
  username: {{ .Values.TestJenkinsUser.Name | b64enc | quote }}
  password: {{ .Values.TestJenkinsUser.Password | b64enc | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: usernamePassword
  name: test-jenkins-user
type: Opaque
{{- end }}