dependencies:
  - name: postgresql
    version: 9.1.1
    repository: https://raw.githubusercontent.com/Dokify/bitnami-charts/defb094c658024e4aa8245622dab202874880cbc/bitnami
    condition: postgresql.enabled
